# https://github.com/marketplace/actions/ssh-deploy
# https://github.com/marketplace/actions/ssh-remote-commands

name: CI

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: 部署到阿里云
        # https://github.com/marketplace/actions/ssh-deploy#configuration
        # 将私钥放到 github secrets.SERVER_SSH_KEY
        # 将公钥放到 ~/.ssh/authorized_keys
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-avzr --delete'
          SOURCE: '.'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: '.git, cypress'

      - name: 重启服务
        uses: appleboy/ssh-action@master
        env:
          WORKDIR: ${{ secrets.WORKDIR }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: WORKDIR
          script: |
            cd $WORKDIR
            yarn run restart
